# Generated by Django 4.0.6 on 2022-08-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPenduduk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=17, unique=True, verbose_name='Nomor Induk Kependudukan (KTP)')),
                ('nama_lengkap', models.CharField(max_length=100, unique=True, verbose_name='Nama Lengkap Pengurus')),
                ('jmlanaksd', models.PositiveSmallIntegerField(verbose_name='Jumlah Anak SD')),
                ('jmlanaksmp', models.PositiveSmallIntegerField(verbose_name='Jumlah Anak SMP')),
                ('jmlanakSMA', models.PositiveSmallIntegerField(verbose_name='Jumlah Anak SMA')),
                ('jmlbumil', models.PositiveSmallIntegerField(verbose_name='Jumlah Ibu Hamil')),
                ('jmlbalita', models.PositiveSmallIntegerField(verbose_name='Jumlah Anak Balita')),
                ('jmlapras', models.PositiveSmallIntegerField(verbose_name='Jumlah Anak Balita dan Prasekolah')),
                ('jmllu', models.PositiveSmallIntegerField(verbose_name='Jumlah Orang Lanjut Usia')),
                ('jmldb', models.PositiveSmallIntegerField(verbose_name='Jumlah Penyandang Disabilitas')),
                ('nmkeca', models.CharField(max_length=100, verbose_name='Nama Kecamatan')),
                ('prediksi_bantuan', models.DecimalField(decimal_places=6, editable=False, max_digits=10, verbose_name='Total Bantuan diterima')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Penduduk',
                'ordering': ['published'],
            },
        ),
    ]
