# Generated by Django 4.0.6 on 2022-08-02 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluasimodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kecamatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_kecamatan', models.CharField(max_length=6, unique=True, verbose_name='Kode Kecamatan')),
                ('nama_kecamatan', models.CharField(max_length=25, verbose_name='Nama Kecamatan')),
            ],
        ),
        migrations.CreateModel(
            name='Kelurahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_kelurahan', models.CharField(max_length=6, unique=True, verbose_name='Kode Kelurahan')),
                ('nama_kelurahan', models.CharField(max_length=25, verbose_name='Nama Kelurahan')),
            ],
        ),
        migrations.AddField(
            model_name='datapenduduk',
            name='alamat',
            field=models.CharField(max_length=150, null=True, verbose_name='Alamat Tempat Tinggal'),
        ),
        migrations.AlterField(
            model_name='datapenduduk',
            name='prediksi_bantuan',
            field=models.DecimalField(decimal_places=6, editable=False, max_digits=10, verbose_name='Total Bantuan diterima (Rp.)'),
        ),
        migrations.AddField(
            model_name='datapenduduk',
            name='nmkelr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluasimodel.kelurahan'),
        ),
        migrations.AlterField(
            model_name='datapenduduk',
            name='nmkeca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluasimodel.kecamatan'),
        ),
    ]
