# Generated by Django 4.0.6 on 2022-08-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluasimodel', '0002_kecamatan_kelurahan_datapenduduk_alamat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kecamatan',
            options={'ordering': ['kode_kecamatan'], 'verbose_name_plural': 'Kecamatan'},
        ),
        migrations.AlterModelOptions(
            name='kelurahan',
            options={'ordering': ['kode_kelurahan'], 'verbose_name_plural': 'Kelurahan'},
        ),
        migrations.AlterField(
            model_name='kecamatan',
            name='nama_kecamatan',
            field=models.CharField(max_length=25, unique=True, verbose_name='Nama Kecamatan'),
        ),
        migrations.AlterField(
            model_name='kelurahan',
            name='nama_kelurahan',
            field=models.CharField(max_length=25, unique=True, verbose_name='Nama Kelurahan'),
        ),
    ]
