# Generated by Django 4.0.6 on 2022-08-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluasimodel', '0003_alter_kecamatan_options_alter_kelurahan_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapenduduk',
            name='prediksi_bantuan',
            field=models.DecimalField(decimal_places=6, editable=False, max_digits=10, null=True, verbose_name='Total Bantuan diterima (Rp.)'),
        ),
    ]
