# Generated by Django 4.0.6 on 2022-08-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluasimodel', '0005_rename_jmlanaksma_datapenduduk_jmlanaksma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapenduduk',
            name='prediksi_bantuan',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Total Bantuan diterima (Rp.)'),
        ),
    ]
