# Generated by Django 4.0.6 on 2022-08-07 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluasimodel', '0006_alter_datapenduduk_prediksi_bantuan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datapenduduk',
            old_name='jmlanaksd',
            new_name='jumlah_anak_sd',
        ),
        migrations.RenameField(
            model_name='datapenduduk',
            old_name='jmlanaksma',
            new_name='jumlah_anak_sma',
        ),
        migrations.RenameField(
            model_name='datapenduduk',
            old_name='jmlanaksmp',
            new_name='jumlah_anak_smp',
        ),
        migrations.RenameField(
            model_name='datapenduduk',
            old_name='jmlbalita',
            new_name='jumlah_balita',
        ),
        migrations.RenameField(
            model_name='datapenduduk',
            old_name='jmlapras',
            new_name='jumlah_balita_anakprasekolah',
        ),
        migrations.RenameField(
            model_name='datapenduduk',
            old_name='jmlbumil',
            new_name='jumlah_ibu_hamil',
        ),
        migrations.RenameField(
            model_name='datapenduduk',
            old_name='jmllu',
            new_name='jumlah_lanjut_usia',
        ),
        migrations.RenameField(
            model_name='datapenduduk',
            old_name='jmldb',
            new_name='jumlah_penyandang_disabilitas',
        ),
        migrations.RenameField(
            model_name='datapenduduk',
            old_name='nmkeca',
            new_name='kecamatan',
        ),
        migrations.RenameField(
            model_name='datapenduduk',
            old_name='nmkelr',
            new_name='kelurahan',
        ),
    ]
