# Generated by Django 4.0.6 on 2022-08-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluasimodel', '0007_rename_jmlanaksd_datapenduduk_jumlah_anak_sd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapenduduk',
            name='prediksi_bantuan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Total Bantuan diterima (Rp.)'),
        ),
    ]
